/// @description Insert description here
// You can write your code in this editor
START_THE_ACTION_TIME = 3
RELEASE_ENEMIES_TIME = 42.5 + START_THE_ACTION_TIME
PAUSE_CHINA_BREATHING_TIME = 99 + START_THE_ACTION_TIME
START_ALL_BREATHING_TIME = 106.9 + START_THE_ACTION_TIME	

//prior alarms
START_THE_ACTION_ALARM = 0
RELEASE_ENEMIES_ALARM = 0
PAUSE_CHINA_BREATHING_ALARM = 0
START_ALL_BREATHING_ALARM = 0
		